-- Q1. What is the total revenue generated by male vs. female customers?

SELECT
    gender,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
    AND purchase_amount > (
        SELECT AVG(purchase_amount)
        FROM customer
    );


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.

SELECT
    shipping_type,
    AVG(purchase_amount) AS avg_spend
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more?
--       Compare average spend and total revenue between
--       subscribers and non-subscribers.

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY
    total_revenue DESC,
    avg_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(
        CASE
            WHEN discount_applied = 'Yes' THEN 1
            ELSE 0
        END
    ) AS discounted_purchases,
    ROUND(
        (
            SUM(
                CASE
                    WHEN discount_applied = 'Yes' THEN 1.0
                    ELSE 0.0
                END
            ) / COUNT(*)
        ) * 100,
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC;


-- Q7. Segment customers into New, Returning, and Loyal
--       based on their total number of previous purchases,
--       and show the count of each segment.

WITH SegmentedCustomers AS
(
    SELECT
        customer_id,
        CASE
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'New'
            WHEN previous_purchases BETWEEN 6 AND 20 THEN 'Returning'
            WHEN previous_purchases BETWEEN 21 AND 50 THEN 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*) AS total_customers
FROM SegmentedCustomers
GROUP BY customer_segment
ORDER BY total_customers DESC;


-- Q8. What are the top 3 most purchased products within each category?

WITH RankedProducts AS
(
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER
        (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS product_rank
    FROM customer
    GROUP BY
        category,
        item_purchased
)
SELECT
    category,
    item_purchased,
    total_purchases,
    product_rank
FROM RankedProducts
WHERE product_rank <= 3
ORDER BY
    category ASC,
    total_purchases DESC;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?

SELECT
    age_group,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;